### ISSUE TITLE
Mechanics ToDo

### ISSUE THREAD

**Issue by psky489527** [Memhir-Yasue/Reddit-Sentiment#1]
- [x] Resolve issue with heading score
- [x] Resolve issue with overall score
- [x] Optimize redditnlp function 1/3
- [x] Optimize redditnlp function 2/3
- [ ] Redditnlp function optimized
- [x] Redditnlp and main page integrated
- [ ] Add weights for different levels of sentiment
- [x] TextBlob vs Vader vs something
- [x] Implement Dash
- [ ] Dash app is it's own .py file
- [x] Create a chaching mechanism to stop long reloads/redundancy.
